import type { Metadata } from "next";
import {Hind} from "next/font/google";
import "./globals.css";

const hind = Hind({
  subsets: ["latin"],
  variable: "--font-hind",
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hind.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
